// Feather disable all



///////
// General
///////

// Which input mode to default to when running on desktop platforms. Must be a `BENTO_MODE_*`
// constant.
#macro BENTO_DESKTOP_DEFAULT_INPUT_MODE  BENTO_MODE_MOUSE

// Whether the primary action should trigger a click on press rather than on release when using a
// pointer. This won't apply if an element has a parent that is scrollable.
#macro BENTO_POINTER_CLICK_ON_PRESS  false

// Whether Bento elements should always execute their Step user event / callback method. Normally
// the Step user event / callback would be skipped if unless an element is a valid button or has
// individually set itself to requiring an update using `BentoSetPushStep()`.
#macro BENTO_ALWAYS_EXECUTE_STEP  false

// Hotkey name used to cancel input. You may check against this macro yourself for general cancel
// behaviour (e.g. to quickly close a pop-up window using a gamepad by pressing a button).
// Conventionally, a "cancel" hotkey is mapped to the escape key on a keyboard or the B button on a
// gamepad.
// 
// This hotkey is also used when receiving text input on a desktop platform from the keyboard (and
// not using Steam's on-screen keyboard). You should use this macro with `BentoInputHotkey()` to
// trigger cancelling text input.
#macro BENTO_HOTKEY_CANCEL  "hotkey cancel"

// Drag & drop when using a pointer input mode (moues or touch) requires the player to click and
// hold as they move the element around. If this macro is set to `true` then pointer input will
// instead behave like navigation input modes where the player clicks and releases once to pick up
// an element and then clicks and releases again to drop the element.
#macro BENTO_DRAG_ALWAYS_TOGGLES  false

// How long, in milliseconds, the primary button must be held down to count as a "long click".
#macro BENTO_LONG_CLICK_TIME  420 //milliseconds



///////
// Layout & Positioning
///////

// Whether to floor (round down to the nearest integer) positions generated by the library's layout
// system. This is helpful for pixel art games.
#macro BENTO_FLOOR_LAYOUT_POSITIONS  true

// Default alignment for elements relative to their parent. This should be a value from `0` (left
// or top) to `1` (right or bottom). A value of `0.5` is therefore the centre/middle of an element.
/// Please see documentation for `BentoLayoutSetAnchor()` for more information.
#macro BENTO_DEFAULT_LAYOUT_ANCHOR_X  0
#macro BENTO_DEFAULT_LAYOUT_ANCHOR_Y  0

// Default alignment for elements relative to their parent. This should be a value from `0` (left
// or top) to `1` (right or bottom). A value of `0.5` is therefore the centre/middle of an element.
// Please see documentation for `BentoLayoutSetAnchor()` for more information.
#macro BENTO_DEFAULT_ORIGIN_X  0
#macro BENTO_DEFAULT_ORIGIN_Y  0



///////
// Scrolling
///////

// How far the pointer must move before engaging scrolling when clicking and dragging.
#macro BENTO_POINTER_DRAG_THRESHOLD  4

// Default speed that scrolling element scroll at. Measured in pixels per frame.
#macro BENTO_DEFAULT_SCROLL_SPEED  7

// Whether clicking and dragging on a scrollable element should scroll in the `BENTO_MODE_MOUSE`
// input mode.
#macro BENTO_SCROLL_ON_MOUSE_DRAG  true

// Padding between the edge of an element and the edge of the clipping window. This will be applied
// to the edges of elements that have been scrolled to (usually via hover when using a keyboard
// or gamepad). This helps improve the visual presentation of the UI.
#macro BENTO_SCROLL_TO_PADDING  10



///////
// Instances
///////

// What depth to create instances on when using `BentoCreate()`. This macro will only be used if
// `BENTO_INSTANCE_LAYER` is set to `undefined`.
#macro BENTO_INSTANCE_DEPTH  0

// What room layer to create instances on when using `BentoCreate()`. Use `undefined` to instead
// create instances using a particular depth, as set by `BENTO_INSTANCE_DEPTH`.
#macro BENTO_INSTANCE_LAYER  undefined



///////
// Mouse Wheel
///////

// How far to scroll when scrolling with a mouse wheel, measured in pixels. Set this value to `0`
// to disable mouse wheel scrolling entirely.
#macro BENTO_MOUSE_WHEEL_SCROLL_SPEED  20

// Hotkey names to use to enable mouse wheel scrolling. This macros should be used with
// `BentoInputHotkey()` to trigger scrolling.
#macro BENTO_HOTKEY_MOUSE_WHEEL_UP    "mouse wheel up"
#macro BENTO_HOTKEY_MOUSE_WHEEL_DOWN  "mouse wheel down"



///////
// Advanced
///////

// Whether to run safety checks for some Bento functions. These error messages can help with
// debugging your code. However, these is a small performance cost. You should consider setting
// this macro to `false` for production builds after thorough testing.
#macro BENTO_SAFE  true

// Controls how much debug information to output. Debug messages can be seen in the "Output" window
// in the GameMaker IDE or via various debug utilities. The following values are supported:
// 
// 0: No additional debug information is shown
// 1: Debug information shown for significant changes in state
// 
// In general, this macro should be set to `0` for production builds. However, if you'd like to see
// additional debug information, e.g. for QA builds, then you can use higher debug levels.
#macro BENTO_DEBUG_LEVEL  1

// Enables `BentoGetEnclosed()` but will impact performance slightly.
#macro BENTO_ALLOW_ENCLOSED_GETTER  false

// Whether to require `BentoCreate()` when creating Bento elements using object instances. If you
// set this macro to `false` then instances that inherit from `oBentoAncestor` but that are not
// created with `BentoCreate()` will be automatically parented to `BentoLayerGetRoot()` (which is
// often correct but not always).
// 
// This macro does not affect Bento elements created using struct constructors.
#macro BENTO_REQUIRE_CREATE  true

// Function to call when parsing strings from `.children` properties in `BentoCreateFromJSON()`.
// Please see documentation for that function for further information.
#macro BENTO_JSON_STRING_PROCESSOR  undefined

// Functions to call when showing debug messages. Set this macro to `undefined` to disable all
// debug messages.
#macro BENTO_SHOW_DEBUG_MESSAGE  show_debug_message

// Function to call when showing errors. (These cannot be disabled!)
#macro BENTO_SHOW_ERROR  show_error

// Variable name that should be used for elements to store private Bento variables.
#macro BENTO_VARS  __bentoVars