#macro BENTO_EXAMPLE_DEFAULT_FONT  fntBentoExCandyBeans
#macro BENTO_EXAMPLE_YELLOW  #ffee75
#macro BENTO_EXAMPLE_BLUE  #4C85ff
#macro BENTO_EXAMPLE_DARK_BLUE  #1657e5
#macro BENTO_EXAMPLE_RED  #ff7575

#macro BENTO_EXAMPLE_SHADOW_ALPHA  0.33
#macro BENTO_EXAMPLE_SHADOW_OFFSET  4
#macro BENTO_EXAMPLE_HIGHLIGHT_SHADOW_ALPHA  0.2
#macro BENTO_EXAMPLE_HIGHLIGHT_SHADOW_OFFSET  2