#macro BENTO_EXAMPLE_DEFAULT_FONT  fntBentoExCandyBeans
#macro BENTO_EXAMPLE_YELLOW  #ffee75
#macro BENTO_EXAMPLE_BLUE  #4C85ff
#macro BENTO_EXAMPLE_DARK_BLUE  #1657e5
#macro BENTO_EXAMPLE_RED  #ff7575