// Feather disable all

// What room layer to create instances on when using `BentoCreateObject()`. Use `undefined` to
// instead create instances using a particular depth see `BENTO_INSTANCE_DEPTH`.
#macro BENTO_INSTANCE_LAYER  undefined

// What depth to create instances on when using `BentoCreateObject()`. This macro will only be used
// if `BENTO_INSTANCE_LAYER` is set to `undefined`.
#macro BENTO_INSTANCE_DEPTH  0

// Whether to floor (round down to the nearest integer) positions generated by the library's layout
// system. This is helpful for pixel art games.
#macro BENTO_FLOOR_LAYOUT_POSITIONS  true

// How far the pointer must move before engaging scrolling when clicking and dragging when using
// `BentoScrollOnPointer()`.
#macro BENTO_SCROLL_THRESHOLD  4

// How far to scroll when scrolling with a mouse wheel. Set this value to `0` to disable mouse
// wheel scrolling (or just don't use `BENTO_HOTKEY_MOUSE_WHEEL_UP` or `BENTO_HOTKEY_MOUSE_WHEEL_DOWN`).
#macro BENTO_MOUSE_WHEEL_SCROLL_SPEED  20

// Whether the primary action should trigger a click on press rather than on release when using a
// pointer. This won't apply if an element has a parent that is scrollable.
#macro BENTO_POINTER_CLICK_ON_PRESS  false

#macro BENTO_FOCUS_BLOCKS_POINTER_HOVER  true

// Whether clicking and dragging on a scrollable UI element should scroll in the `BENTO_MODE_MOUSE`
// nav mode.
#macro BENTO_SCROLL_ON_MOUSE_DRAG  true

// Button names to use to enable mouse wheel scrolling with `BentoScrollOnPointer()`. This macros
// should be used with `BentoInputHotkey()` to trigger scrolling.
#macro BENTO_HOTKEY_MOUSE_WHEEL_UP    "mouse wheel up"
#macro BENTO_HOTKEY_MOUSE_WHEEL_DOWN  "mouse wheel down"

// Which navigation mode to default to when running on desktop platforms. Must be a `BENTO_MODE_*`
// constant.
#macro BENTO_DESKTOP_DEFAULT_NAV_MODE  BENTO_MODE_MOUSE

// Debug only. Set this macro to `true` to show verbose output in the debug log that shows which
// instances are being hovered / un-hovered.
#macro BENTO_VERBOSE_HOVER_STATE  false

// Functions to call when showing debug messages. Set this macro to `undefined` to disable all
// debug messages.
#macro BENTO_SHOW_DEBUG_MESSAGE  show_debug_message

// Function to call when showing errors. (These cannot be disabled!)
#macro BENTO_SHOW_ERROR  show_error

#macro BENTO_JSON_CHILDREN_STRING_PROCESSOR  undefined

#macro BENTO_DEFAULT_LAYOUT_ALIGN_H  0
#macro BENTO_DEFAULT_LAYOUT_ALIGN_V  0

#macro BENTO_SCROLL_TO_PADDING  10

#macro BENTO_DEFAULT_SCROLL_SPEED  8

#macro BENTO_VARS  __bentoVars

#macro BENTO_ALWAYS_EXECUTE_STEP  false