// Feather disable all



///////
// General
///////

// Which input mode to default to when running on desktop platforms. Must be a `BENTO_MODE_*`
// constant.
#macro BENTO_DESKTOP_DEFAULT_NAV_MODE  BENTO_MODE_MOUSE

// Whether the primary action should trigger a click on press rather than on release when using a
// pointer. This won't apply if an element has a parent that is scrollable.
#macro BENTO_POINTER_CLICK_ON_PRESS  false

// What happens when the cursor hovers other elements but those elements are blocked due to some
// focus setting.
#macro BENTO_FOCUS_BLOCKS_POINTER_HOVER  true

// Whether Bento elements should always execute their Step user event / callback method. Normally
// the Step user event / callback would be skipped if unless an element is a valid button or has
// individually set itself to requiring an update using `BentoSetForceStep()`.
#macro BENTO_ALWAYS_EXECUTE_STEP  false



///////
// Layout
///////

// Whether to floor (round down to the nearest integer) positions generated by the library's layout
// system. This is helpful for pixel art games.
#macro BENTO_FLOOR_LAYOUT_POSITIONS  true

// Default alignment for elements relative to their parent. This should be a value from `0` (left
// or top) to `1` (right or bottom). Please see documentation for `BentoLayoutSetAlignSelf()` for
// more information.
#macro BENTO_DEFAULT_LAYOUT_ALIGN_H  0
#macro BENTO_DEFAULT_LAYOUT_ALIGN_V  0



///////
// Scrolling
///////

// How far the pointer must move before engaging scrolling when clicking and dragging when using
// `BentoScrollOnPointer()`.
#macro BENTO_SCROLL_THRESHOLD  4

// Default speed that scrolling element scroll at. Measured in pixels per frame.
#macro BENTO_DEFAULT_SCROLL_SPEED  8

// Whether clicking and dragging on a scrollable element should scroll in the `BENTO_MODE_MOUSE`
// nav mode.
#macro BENTO_SCROLL_ON_MOUSE_DRAG  true

// Padding to apply around the edges of elements have been scrolled to. This ensures that elements
// are pleasantly visible.
#macro BENTO_SCROLL_TO_PADDING  10



///////
// Instances
///////

// What room layer to create instances on when using `BentoCreateObject()`. Use `undefined` to
// instead create instances using a particular depth see `BENTO_INSTANCE_DEPTH`.
#macro BENTO_INSTANCE_LAYER  undefined

// What depth to create instances on when using `BentoCreateObject()`. This macro will only be used
// if `BENTO_INSTANCE_LAYER` is set to `undefined`.
#macro BENTO_INSTANCE_DEPTH  0



///////
// Mouse Wheel
///////

// How far to scroll when scrolling with a mouse wheel, measured in pixels. Set this value to `0`
// to disable mouse wheel scrolling (or just don't use `BENTO_HOTKEY_MOUSE_WHEEL_UP` or
// `BENTO_HOTKEY_MOUSE_WHEEL_DOWN`).
#macro BENTO_MOUSE_WHEEL_SCROLL_SPEED  20

// Button names to use to enable mouse wheel scrolling with `BentoScrollOnPointer()`. This macros
// should be used with `BentoInputHotkey()` to trigger scrolling.
#macro BENTO_HOTKEY_MOUSE_WHEEL_UP    "mouse wheel up"
#macro BENTO_HOTKEY_MOUSE_WHEEL_DOWN  "mouse wheel down"



///////
// Advanced
///////

// Function to call when parsing strings from `.children` properties in `BentoCreateFromJSON()`.
// Please see documentation for that function for further information.
#macro BENTO_JSON_CHILDREN_STRING_PROCESSOR  undefined

// Debug only. Set this macro to `true` to show verbose output in the debug log that shows which
// elements are being hovered / un-hovered.
#macro BENTO_VERBOSE_HOVER_STATE  false

// Functions to call when showing debug messages. Set this macro to `undefined` to disable all
// debug messages.
#macro BENTO_SHOW_DEBUG_MESSAGE  show_debug_message

// Function to call when showing errors. (These cannot be disabled!)
#macro BENTO_SHOW_ERROR  show_error

// Variable name that should be used for elements to store private Bento variables.
#macro BENTO_VARS  __bentoVars